--
-- PostgreSQL database dump
--

\restrict JKPydsRpDUVebzRmCBveyqpRHWOXlcrpakKVKXVTB1QfHFfnvhyrgaYXX7Mw2VR

-- Dumped from database version 17.10 (Homebrew)
-- Dumped by pg_dump version 17.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grade_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grade_mapping (
    id bigint NOT NULL,
    active boolean,
    confidence double precision,
    difficulty_score double precision,
    discipline character varying(255),
    grade_system character varying(255),
    raw_grade character varying(255),
    system_order double precision,
    note character varying(1000),
    CONSTRAINT grade_mapping_discipline_check CHECK (((discipline)::text = ANY ((ARRAY['BOULDER'::character varying, 'SPORT'::character varying, 'TRAD'::character varying, 'ICE'::character varying, 'MIXED'::character varying, 'AID'::character varying, 'GYM'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT grade_mapping_grade_system_check CHECK (((grade_system)::text = ANY ((ARRAY['V_SCALE'::character varying, 'FONT'::character varying, 'YDS'::character varying, 'FRENCH_SPORT'::character varying, 'ICE_WI'::character varying, 'MIXED_M'::character varying, 'AID'::character varying, 'E_Grade'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: grade_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grade_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_batch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_batch (
    id bigint NOT NULL,
    failed_rows integer,
    imported_at timestamp(6) without time zone NOT NULL,
    original_filename character varying(255),
    source_app character varying(255),
    successful_rows integer,
    total_rows integer,
    user_id bigint,
    CONSTRAINT import_batch_source_app_check CHECK (((source_app)::text = ANY ((ARRAY['MANUAL'::character varying, 'MOUNTAIN_PROJECT'::character varying, 'KAYA'::character varying, 'EIGHT_A'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: import_batch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tick; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tick (
    id bigint NOT NULL,
    attempts integer,
    climb_height double precision,
    climb_id character varying(255),
    climb_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    discipline character varying(255),
    external_id character varying(255),
    grade character varying(255),
    grade_system character varying(255),
    grade_value double precision,
    location character varying(255),
    notes character varying(2000),
    personal_grade character varying(255),
    pitches integer,
    raw_grade character varying(255),
    rope_style character varying(255),
    source_app character varying(255),
    source_url character varying(255),
    stars double precision,
    style character varying(255),
    tick_date date,
    tick_type character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    user_stars double precision,
    grade_mapping_id bigint,
    user_id bigint,
    CONSTRAINT tick_discipline_check CHECK (((discipline)::text = ANY ((ARRAY['BOULDER'::character varying, 'SPORT'::character varying, 'TRAD'::character varying, 'ICE'::character varying, 'MIXED'::character varying, 'AID'::character varying, 'GYM'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT tick_grade_system_check CHECK (((grade_system)::text = ANY ((ARRAY['V_SCALE'::character varying, 'FONT'::character varying, 'YDS'::character varying, 'FRENCH_SPORT'::character varying, 'ICE_WI'::character varying, 'MIXED_M'::character varying, 'AID'::character varying, 'E_Grade'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT tick_rope_style_check CHECK (((rope_style)::text = ANY ((ARRAY['FLASH'::character varying, 'ONSIGHT'::character varying, 'REDPOINT'::character varying, 'PINKPOINT'::character varying, 'REPEAT'::character varying, 'SOLO'::character varying, 'LRS'::character varying, 'FS'::character varying, 'OSFS'::character varying, 'DS'::character varying, 'FB'::character varying, 'DWS'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT tick_source_app_check CHECK (((source_app)::text = ANY ((ARRAY['MANUAL'::character varying, 'MOUNTAIN_PROJECT'::character varying, 'KAYA'::character varying, 'EIGHT_A'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT tick_tick_type_check CHECK (((tick_type)::text = ANY ((ARRAY['SEND'::character varying, 'ATTEMPT'::character varying, 'CLEAN_TR'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: tick_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tick ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tick_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: grade_mapping grade_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade_mapping
    ADD CONSTRAINT grade_mapping_pkey PRIMARY KEY (id);


--
-- Name: import_batch import_batch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_batch
    ADD CONSTRAINT import_batch_pkey PRIMARY KEY (id);


--
-- Name: tick tick_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tick
    ADD CONSTRAINT tick_pkey PRIMARY KEY (id);


--
-- Name: app_users uk4vj92ux8a2eehds1mdvmks473; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT uk4vj92ux8a2eehds1mdvmks473 UNIQUE (email);


--
-- Name: grade_mapping uk_grade_mapping_system_discipline_raw_grade; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade_mapping
    ADD CONSTRAINT uk_grade_mapping_system_discipline_raw_grade UNIQUE (grade_system, discipline, raw_grade);


--
-- Name: import_batch fk2fk6l1359fpqbsl72l6mdaj8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_batch
    ADD CONSTRAINT fk2fk6l1359fpqbsl72l6mdaj8d FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: tick fkilvbmhxevn0m1q4rq2we1bemv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tick
    ADD CONSTRAINT fkilvbmhxevn0m1q4rq2we1bemv FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: tick fkoypdgco7eye3ppea2b2wkm21r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tick
    ADD CONSTRAINT fkoypdgco7eye3ppea2b2wkm21r FOREIGN KEY (grade_mapping_id) REFERENCES public.grade_mapping(id);


--
-- PostgreSQL database dump complete
--

\unrestrict JKPydsRpDUVebzRmCBveyqpRHWOXlcrpakKVKXVTB1QfHFfnvhyrgaYXX7Mw2VR

