CREATE TABLE public.skipped_row (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_number bigint NOT NULL,
    reason text,
    raw_row text,
    import_batch_id bigint NOT NULL
);

ALTER TABLE ONLY public.skipped_row
    ADD CONSTRAINT fk_skipped_row_import_batch
    FOREIGN KEY (import_batch_id) REFERENCES public.import_batch(id);
